repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Replace this with the latest version if needed
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 23.1.0  # Replace this with the latest version if needed
    hooks:
      - id: black
        language_version: python3
